name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        
      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest
     
      - name: Nuget Restore 
        run: nuget restore
        
      - name: Build
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe "$Env:GITHUB_WORKSPACE\uMapProject.sln" -p:TargetFramework=net40
           
      - uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: ./uMap/bin/Debug

      - name: Create ZIP
        shell: pwsh
        run: |
          cd $Env:GITHUB_WORKSPACE\uMap\bin\
          mv Debug uMap
          Compress-Archive -Path .\uMap -DestinationPath uMap-win-x64.zip
          dir

      - name: Publish artefacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '$Env:GITHUB_WORKSPACE/uMap/bin/uMap-win-x64.zip'
          asset_name: 'uMap-win-x64.zip'
          tag: ${{ github.ref }}
          overwrite: true
